// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVDbsE5d-PXRnZfLlGKWDfPVTZnnOeqkA',
    appId: '1:1076338800113:web:b8d55c17963735bdd0c050',
    messagingSenderId: '1076338800113',
    projectId: 'flutter-furniture-app-5aae2',
    authDomain: 'flutter-furniture-app-5aae2.firebaseapp.com',
    storageBucket: 'flutter-furniture-app-5aae2.appspot.com',
    measurementId: 'G-6VL9KBQPW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA78fw3ll_e3gNNtiFdT_UjTCfNeMcT_NM',
    appId: '1:1076338800113:android:7aa4fc8141bb6350d0c050',
    messagingSenderId: '1076338800113',
    projectId: 'flutter-furniture-app-5aae2',
    storageBucket: 'flutter-furniture-app-5aae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg0XPCs1-n-5tYrxRaEJybFmuIYBYqWhY',
    appId: '1:1076338800113:ios:a9b2fc3f3d9309ccd0c050',
    messagingSenderId: '1076338800113',
    projectId: 'flutter-furniture-app-5aae2',
    storageBucket: 'flutter-furniture-app-5aae2.appspot.com',
    iosBundleId: 'com.example.flutterFurnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg0XPCs1-n-5tYrxRaEJybFmuIYBYqWhY',
    appId: '1:1076338800113:ios:a9b2fc3f3d9309ccd0c050',
    messagingSenderId: '1076338800113',
    projectId: 'flutter-furniture-app-5aae2',
    storageBucket: 'flutter-furniture-app-5aae2.appspot.com',
    iosBundleId: 'com.example.flutterFurnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVDbsE5d-PXRnZfLlGKWDfPVTZnnOeqkA',
    appId: '1:1076338800113:web:968e208e2c08c09ad0c050',
    messagingSenderId: '1076338800113',
    projectId: 'flutter-furniture-app-5aae2',
    authDomain: 'flutter-furniture-app-5aae2.firebaseapp.com',
    storageBucket: 'flutter-furniture-app-5aae2.appspot.com',
    measurementId: 'G-YHR1XX2SZW',
  );
}
