name: flutter_furniture_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.2
  dio: ^5.5.0+1
  google_fonts: ^6.2.1
  card_swiper: ^3.0.1
  font_awesome_icon_class: ^0.0.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_analytics: ^10.8.0
  cloud_firestore: ^4.14.0
  get_it: ^7.7.0
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  flutter_login_facebook: ^2.0.1
  flutter_screenutil: ^5.9.3
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/model.json
    - assets/images/koltuk1.jpg
    - assets/images/yatak1.jpg
    - assets/images/yemek.jpg
    - assets/images/bahce.jpg
    - assets/images/koltuk2.jpg
    - assets/images/bahcetakim.jpg
    - assets/images/login.jpg
    - assets/images/google-icon.png
    - assets/images/Facebook-icon.png
    - assets/images/images.jpeg
    - assets/images/furniture-background.jpg
